[Issue 12] Spam Handling
nitechdesign/code-of-conduct pull request #22
Opened 2018-05-05 13:34 UTC by mauricerkelly

In response to Issue #12 and in light of events this last week, I've written up some stuff about what we consider spam and how we will deal with it.

2018-05-06 15:10 UTC, MarkXA approved these changes

2018-05-06 16:04 UTC, clairebones approved these changes

2018-05-07 11:55 UTC, mauricerkelly commented
@andrewbolster I'd feel happier about merging this with your approval, since you raised the issue that it was based on.

2018-05-08 09:44 UTC, andrewbolster requested changes

2018-05-08 09:44 UTC, andrewbolster commented on code-of-conduct.md
> +In the event of an activity considered to be spam being reported to the admins, a request will be made to the member responsible to rectify their actions (by removing messages, emoji, bots, etc) and
could do with an addition of 'within a timely fashion' to the "Failure to rectify" phrase.  Other than that LGTM

2018-05-29 19:46 UTC, mauricerkelly commented
@andrewbolster requested change has been carried out.

2018-06-10 12:18 UTC, mauricerkelly commented
@andrewbolster still waiting on a re-review from you. Cheers.

2018-06-19 12:29 UTC, andrewbolster approved these changes

2018-06-19 12:29 UTC, merged