Promotion of abuse and discrimination
nitechdesign/code-of-conduct pull request #9
Opened 2018-02-27 10:39 UTC by nitech-code-of-conduct-suggestions-2

"Offensive comments" is too vague to call out promoting discrimination (like links or tweets to pub/controversy pieces by racist, sexist or homophic groups), that hide under "free speech". This backs us up in rejecting that kind of content when admins see it's necessary.

Could be in different place in list, but then would need characteristics list copied.

2018-03-06 20:25 UTC, mauricerkelly commented
I think this would be better served if it included an example of what is considered to be promotion of abuse.

2018-04-08 09:28 UTC, mauricerkelly requested changes
Another couple of comments here:
- what are "pub/controversy pieces" - specifically "pub"? Maybe "controversial pieces" would be sufficient?
- is this a typo in "homophic"?

2018-04-08 13:32 UTC, MarkXA reviewed
This should probably be moved from "Harassment" to an "Unacceptable behaviour" section. Possibly rephrase to something like "Supporting or promoting behaviour or statements that do not comply with this Code of Conduct".

2018-04-14 12:39 UTC, nitech-code-of-conduct-suggestions-2 commented
Just made those changes - thank you mo for pointing out typo.

2018-04-22 19:34 UTC, mauricerkelly approved these changes

2018-04-28 17:34 UTC, mauricerkelly commented
I've resolved a merge conflict here. Can we get some (dis/)approvals to move it along?

2018-04-28 17:39 UTC, clairebones approved these changes

2018-04-29 17:07 UTC, merged